//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.296
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTPViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FTPViewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;!DOCTYPE ROOT
        ///	[
        ///  &lt;!ELEMENT ROOT (SERVER)*&gt;
        ///  &lt;!ELEMENT SERVER (ID, ADDRESS, PORT, SRVDIR, SAVEDIR, FILE, LOGIN, PASS)&gt;
        ///  &lt;!ELEMENT ADDRESS (#PCDATA)&gt;
        ///  &lt;!ELEMENT PORT (#PCDATA)&gt;
        ///  &lt;!ELEMENT SRVDIR (#PCDATA)&gt;
        ///  &lt;!ELEMENT SAVEDIR (#PCDATA)&gt;
        ///  &lt;!ELEMENT FILE (#PCDATA)&gt;
        ///  &lt;!ELEMENT LOGIN (#PCDATA)&gt;
        ///  &lt;!ELEMENT PASS (#PCDATA)&gt;
        ///]
        ///&gt;
        ///&lt;!--File name: FTPServerList.xml--&gt;
        ///&lt;ROOT&gt;
        ///  &lt;SERVER id=&quot;1&quot;&gt;
        ///    &lt;ADDRESS&gt;82.162.90.178&lt;/ADDRESS&gt;
        ///    &lt;PORT&gt;21&lt;/PORT&gt;
        ///     [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string FTPServersList {
            get {
                return ResourceManager.GetString("FTPServersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;!DOCTYPE ROOT
        ///	[
        ///  &lt;!ELEMENT ROOT (SERVER)*&gt;
        ///  &lt;!ELEMENT SERVER (ID, ADDRESS, PORT, TYPE, AUTENT, LOGIN, PASS)&gt;
        ///  &lt;!ELEMENT ADDRESS (#PCDATA)&gt;
        ///  &lt;!ELEMENT PORT (#PCDATA)&gt;
        ///  &lt;!ELEMENT TYPE (#PCDATA)&gt;
        ///  &lt;!ELEMENT AUTENT (#PCDATA)&gt;
        ///  &lt;!ELEMENT LOGIN (#PCDATA)&gt;
        ///  &lt;!ELEMENT PASS (#PCDATA)&gt;
        ///]
        ///&gt;
        ///&lt;!--File name: ProxyList.xml--&gt;
        ///&lt;ROOT&gt;
        ///  &lt;SERVER id=&quot;1&quot;&gt;
        ///    &lt;ADDRESS&gt;41.66.242.18&lt;/ADDRESS&gt;
        ///    &lt;PORT&gt;8080&lt;/PORT&gt;
        ///    &lt;TYPE&gt;0&lt;/TYPE&gt;
        ///    &lt;AUTENT&gt;NO&lt;/AUTENT&gt;
        ///    [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ProxyList {
            get {
                return ResourceManager.GetString("ProxyList", resourceCulture);
            }
        }
    }
}
